---
name: Acme-CPANAuthors-Acme-CPANAuthors-Authors
version: 0.1239933158
author:
  - 'Sanko Robinson <sanko@cpan.org>'
abstract: We are CPAN authors who have authored Acme::CPANAuthors modules
license: artistic_2
resources:
  ChangeLog: http://code.google.com/p/sanko/source/list
  bugtracker: http://code.google.com/p/sanko/issues/list
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: http://code.google.com/p/sanko/source/browse/#svn/trunk/Acme-CPANAuthors-Acme-CPANAuthors-Authors
requires:
  Acme::CPANAuthors: 0
  Acme::CPANAuthors::Register: 0
  perl: 5.006
build_requires:
  Test::More: 0
provides:
  Acme::CPANAuthors::Acme::CPANAuthors::Authors:
    file: lib/Acme/CPANAuthors/Acme/CPANAuthors/Authors.pm
    version: 0.1239933158
generated_by: 'Conversion, software version 7.0'
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - Acme
  - CPAN
  - CPANAuthors
  - Authors
  - stupid
  - vanity
  - module
